package com.example.android.tourguide.entity;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Created by ammar_saaddine on 14.03.18.
 */

public class AttractionEntry implements Parcelable {

    // Private variables

    /// Entry title
    private String title;
    /// Entry subtitle
    private String subtitle;
    /// Entry image resource id
    private int imageResourceID;
    /// Entry url to relevant website (https://www.visitberlin.de/en/) page
    private String url;

    // Constructor

    public AttractionEntry(String title, String subtitle, int imageResourceID, String url) {
        this.title = title;
        this.subtitle = subtitle;
        this.imageResourceID = imageResourceID;
        this.url = url;
    }

    // Public methods

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    public int getImageResourceID() {
        return imageResourceID;
    }

    public void setImageResourceID(int imageResourceID) {
        this.imageResourceID = imageResourceID;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }


    // All generated by parcelable

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.title);
        dest.writeString(this.subtitle);
        dest.writeInt(this.imageResourceID);
        dest.writeString(this.url);
    }

    protected AttractionEntry(Parcel in) {
        this.title = in.readString();
        this.subtitle = in.readString();
        this.imageResourceID = in.readInt();
        this.url = in.readString();
    }

    public static final Parcelable.Creator<AttractionEntry> CREATOR = new Parcelable.Creator<AttractionEntry>() {
        @Override
        public AttractionEntry createFromParcel(Parcel source) {
            return new AttractionEntry(source);
        }

        @Override
        public AttractionEntry[] newArray(int size) {
            return new AttractionEntry[size];
        }
    };
}
